Website design
renuo/deploio-landing-page pull request #1
Opened 2023-10-17 14:13 UTC by CuddlyBunion341

# Website styling

## Features

- navbar
- intro section
- technology section
- recommendations section
- comparison section placeholder
- support section
- very basic footer

<details>
<summary>Screenshots</summary>

</details>

<details>
<summary>Canva page</summary>

https://deploio.my.canva.site
![Screenshot 2023-10-17 at 16 39 01](https://github.com/renuo/deplo.io-landing-page/assets/53896675/cd513733-b113-4033-9b2c-4f409bb592ba)

</details>

2023-10-17 15:24 UTC, hunchr requested changes
the website isn't responsive but I assume you're still working on that

2023-10-17 15:24 UTC, hunchr commented on src/css/style.css
> +    overflow-x: visible;
Isn't `overflow-x` visible by default?

2023-10-17 15:24 UTC, hunchr commented on src/css/style.css
> +    display: none;
If you want an element to only be visible for screen readers you could use something like this:
```css
clip: rect(1px 1px 1px 1px)
height: 1px
overflow: hidden
width: 1px
```
otherwise it'll be ignored

2023-10-17 15:24 UTC, hunchr commented on src/css/style.css
> +    &, & * {
nesting [still isn't supported everywhere](https://caniuse.com/css-nesting)

2023-10-17 15:24 UTC, hunchr commented on src/css/style.css
> +        align-items: center;
you are using these `center` lines for multiple elements. you could create a new class `.center` instead

2023-10-17 15:24 UTC, hunchr commented on src/css/style.css
> +    gap: 75px;
don't hard-code such a large gap

2023-10-17 15:24 UTC, hunchr commented on src/css/style.css
> +}
unused code

2023-10-17 15:24 UTC, hunchr commented on src/css/style.css
> +    --margin: calc(-1 * calc(100vw - var(--content-width)) / 2);
the 2nd calc is redundant (i.e. `calc(-1 * (100vw - var(--content-width)) / 2)`) but this approach feels kinda hacky anyway

2023-10-17 15:24 UTC, hunchr commented on src/css/style.css
> +}
if you have ~drills~ utils for this you could use them for e.g. `.certificate` instead of writing the line again

2023-10-17 15:24 UTC, hunchr commented on src/css/style.css
> +}
is there a reason why you switch between `rem`, `em` and `px`?

2023-10-17 15:24 UTC, hunchr commented on src/index.html
> +            <img class="img img-wave-logo" src="../assets/images/deploio_wave_logo.png">
`alt` is missing

2023-10-18 06:34 UTC, cb341 commented on src/css/style.css
> +    overflow-x: visible;
true, for debug purposes I unset it from `hidden`...
Thanks for noticing!

2023-10-18 06:34 UTC, cb341 commented on src/index.html
> +            <img class="img img-wave-logo" src="../assets/images/deploio_wave_logo.png">
Thanks for noticing

2023-10-18 06:35 UTC, cb341 commented on src/css/style.css
> +    &, & * {
I know, should I default to SASS and transpile it to css?

2023-10-18 06:36 UTC, cb341 commented on src/css/style.css
> +        align-items: center;
Sure, this could be refactored in Sass with a mixin. I am still thinking about migrating to scss.

2023-10-18 06:36 UTC, cb341 commented on src/css/style.css
> +    gap: 75px;
What should I do otherwise?

2023-10-18 06:36 UTC, cb341 commented on src/css/style.css
> +}
Thx

2023-10-18 06:37 UTC, cb341 commented on src/css/style.css
> +    --margin: calc(-1 * calc(100vw - var(--content-width)) / 2);
It is, might as well consider adding `reduced-width` class to all sections that shouldn't take up 100% of the viewport width.

2023-10-18 06:37 UTC, cb341 commented on src/css/style.css
> +}
Drills?

2023-10-18 06:38 UTC, cb341 commented on src/css/style.css
> +}
Not in particular, no haha

2023-10-18 11:19 UTC, hunchr commented on src/css/style.css
> +}
*utils for these classes (sry, autocorrect)

2023-10-23 09:42 UTC, firemind commented on public/assets/images/language_ruby.png
@coorasse didn't you mention something about the rails logo having to stay red? Or does this not apply here?

2023-10-23 09:48 UTC, CuddlyBunion341 commented on public/assets/images/language_ruby.png
Thanks for the info, I'll quickly discuss this with Yessin.

2023-10-23 10:01 UTC, firemind requested changes

2023-10-23 10:01 UTC, firemind commented on public/index.html
> +            <!--            <a href="#"><img src="assets/images/swiss.png" alt="swiss made, swiss hosting"></a>-->
Why is this commented out. do we need it?

2023-10-23 10:01 UTC, firemind commented on public/index.html
> +</html>
Putting this page through https://validator.w3.org/nu/#textarea shows a couple of pretty basic improvements you can make (like adding a `<title>` and `alt` attributes on images.

2023-10-23 10:01 UTC, firemind commented on src/style.scss
> +      //justify-content: center;
Commented out code

2023-10-23 10:01 UTC, firemind commented on public/index.html
> +                    href="https://cockpit.nine.ch/en/session/new?origin=%2F"
This entire page is in german but the "Sign in" and "Sign Up" are in english and this link points to the english sign in page.

2023-10-23 13:53 UTC, CuddlyBunion341 commented on public/index.html
> +            <!--            <a href="#"><img src="assets/images/swiss.png" alt="swiss made, swiss hosting"></a>-->
No, we no longer do.

2023-10-23 13:56 UTC, CuddlyBunion341 commented on public/index.html
> +</html>
I added the title tag, alt attributes, but I don't know what's up with the article headings.

The outline looks correct:
![CleanShot 2023-10-23 at 15 55 18@2x](https://github.com/renuo/deploio-landing-page/assets/53896675/8a612077-c418-4a11-8da5-e44b2b475e31)
![CleanShot 2023-10-23 at 15 55 10@2x](https://github.com/renuo/deploio-landing-page/assets/53896675/a43709fa-2382-452e-b44d-6da50a26cbb4)

The article is sections into `section` elements, each with its own `h2, h3` tags. Is the <h1> not allowed to be inside a `section` tag?

2023-10-23 13:57 UTC, CuddlyBunion341 commented on public/index.html
> +                    href="https://cockpit.nine.ch/en/session/new?origin=%2F"
Thanks for noticing. The navigation elements will remain in english, but I will update the link.

2023-10-23 14:04 UTC, firemind commented on public/index.html
> +</html>
Yes, it is recommended to have exactly one `h1` per page and have that be above the `section` elements. The sections sub-divide the document while the `h1` is supposed to be the title of the entire document.

2023-10-23 14:09 UTC, cb341 commented on public/index.html
> +</html>
Alright, I replaced the `<section>` tag with a `<div>` and this has improved the whole situation.

2023-10-23 14:10 UTC, CuddlyBunion341 commented on public/index.html
> +</html>
![CleanShot 2023-10-23 at 16 10 06@2x](https://github.com/renuo/deploio-landing-page/assets/53896675/c59bcb12-62d7-4b71-9628-59df793bad8a)

2023-10-23 14:13 UTC, firemind approved these changes

2023-10-23 14:26 UTC, merged